name: account_ledger_cli_dart
description: A sample command-line application with basic argument parsing.
version: 0.0.1

publish_to: none

environment:
  sdk: ^3.3.0-239.0.dev

dependencies:
  args: ^2.4.2
  account_ledger_library:
    path: account_ledger_library_dart
  tuple: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
